name: Build and Deploy Dockerized PHP App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 412phpapp412
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # path to Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Build and deploy Docker container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: Dockerfile
